### ISSUE TITLE
Don't commit on develop / use feature model / revert commits

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectD_Group5#1]
@kajo404 you commited on the develop branch (30f46fe6fdd9c72eebd14f4fbd96b095624d68fc), this is not what you should do.

Please:
- [x] Revert your commit and bring develop back to the initial state ( 1ada3a13b8a31d24e2381de0a4e184dbf8932b42 )
- [x] Open a branch for the feature you work on, branching off from develop
- [x] If you are already done with your feature, open a pull request

We would like you to implement the feature model. If you don't know how this works, please have a look at https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow/ and the video in which I explain it https://youtu.be/twKtSfLcKxI?t=12m25s
# I need to see pull request to know: who did what

:dancer: hope this makes you understand why I do this :D

**Comment by kajo404** [comment]
Hi, sorry for the mess. I think I reverted the github, please let me know if I messed it up again.

**Comment by Logarythms** [comment]
Can we approve the pull requests within our team or do we have to wait for you to check them Christian?

**Comment by sacdallago** [comment]
You can approve them within the team but another person w.r.t. who opens the request.

Everything is fine now! Go on working like this ;)
