### ISSUE TITLE
[HELP] Github has duplicate files

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#11]
Hello Christian,

I somehow have duplicate files in my branch /twitter-stream-api). There is a training.js and training.js~. How do I resolve this?

Greetings

Jonas

**Comment by sacdallago** [comment]
I guess the file is not showing up on your file browser, is that why you are asking?

`cd` into the folder and `git rm training.js~`. This should both delete the file from your computer and from git.
Close the issue if it worked, or let me know.

Cheers
