### ISSUE TITLE
Who reverted the github and why?

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#13]
@Logarythms  @vanp33

**Comment by kajo404** [comment]
@sacdallago can this be undone?

**Comment by sacdallago** [comment]
Which branch? Which commit? What has been reverted?

If you still have the version that you want on your local git, then you can fast-forward to that. I need more context to tell you if this is possible

**Comment by kajo404** [comment]
Well basically the work of the last 4 days is gone. There was a branch "database" which we merged to develop via pull request and everything I did on my branch has been reverted aswell. It looks like somebody just turned back time

**Comment by sacdallago** [comment]
You mean this guy? https://github.com/Rostlab/JS16_ProjectD_Group5/pull/12#event-582015544

You can re-open the branch, re pull-request and re-merge the branch. Git **never** gets rid of anything, so: don't worry.

More importantly I would like to know what happened, who did this and why. You are four people, of which I guess just three could have done this: @Logarythms @vanp33 @jonny3576 ?
You are not gonna get fired :laughing: just please explain

**Comment by kajo404** [comment]
Yes that pull request is gone and also the one before, where we merged the sentiment analysis. After i finished the presentation yesterday I went for a shower and when i came back everything was gone :D.

I will re-open the branch and do another pull request.

Can such a revert happen "by accident"?

**Comment by vanp33** [comment]
Just the database branch? i update something on Vis. branch last night

**Comment by sacdallago** [comment]
Well :D there are 2 levels of accident here: reverting on your machine and then pushing the code to the remote. Or even more work: go into the pull request and press on "revert" for the two PR. Either of which is not too nice without any warning :D

**Comment by gyachdav** [comment]
Isn't it time you closed this one?

**Comment by jcebel** [comment]
As nobody seems to feel guilty ;)
