### ISSUE TITLE
JSHint

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectD_Group5#18]
Hey :) I've finally set up Grunt and Travis.
They are now linting your code... Please check the build results.
If you have preferrences which 'Error' shouldn't be one - e.g. fall-through or curly brackets around every block - Please notify me here :)

**Comment by kajo404** [comment]
What does that mean for us? Do we have to change anyting in our code? I finished working on my branch and created a pull request just before you added grunt and travis. Please take a look at my pull request #15 . If i dont need to change anything just go ahead and approve it otherwise just respond here :)

**Comment by jcebel** [comment]
Well if you look at this: https://travis-ci.org/Rostlab/JS16_ProjectD_Group5 (hope the link works), you'll see that there are some errors in editstring sentimentAnalysis and twitterStreamingApi (all in directory logic).
Please pull the new code to your branches so the testing will be working, when you create an pull request and you see immediately what's not working. (Hopefully)

**Comment by sacdallago** [comment]
You can also run grunt locally to see if everything in the code is alright _before_ you commit. Please @jonny3576 explain how ;)

P.S.: @jonny3576 also put the build label in the readme

**Comment by jcebel** [comment]
well you need to install the npm form grunt-cli globally with
npm install grunt-cli -g
Once you've installed it and you have the gruntfile.js and the package.json in your local repository cloned you may run the tests with
grunt test
I didn't set a default as I wasn't sure if it is needed, so you have to use "test" as option, like i wrote

@sacdallago: Do you mean the link?

**Comment by kajo404** [comment]
when I try to run 

> grunt test

I get the following error: 

> grunt test
> grunt-cli: The grunt command line interface. (v0.1.13)
> 
> Fatal error: Unable to find local grunt.
> 
> If you're seeing this message, either a Gruntfile wasn't found or grunt
> hasn't been installed locally to your project. For more information about
> installing and configuring grunt, please see the Getting Started guide:
> 
> http://gruntjs.com/getting-started

This is cool stuff, I think I understand the idea behind it. Now I just need to get it to work on my machine

**Comment by jcebel** [comment]
Did you first run npm installer?
npm install grunt -g
npm install grunt-cli -g
And do you need to have in your project's root directory the Gruntfile.js -file, which I load into the develop branch

**Comment by kajo404** [comment]
I ran both commands again and I am in the root folder of the project where the gruntfile.js is. Still getting the same error message.

**Comment by jcebel** [comment]
Oh man... Maybe the reason is that you need grunt locally installed.
Let's try this:
Github/YourLocalProjectD5Dir
npm install grunt 

Before you install something you may check what is installed with:
npm ls --depth=0   (Shows your locally installed packages)
npm ls -g --depth=0 (Shows your globally installed packages)
The grunt-cli HAS to be installed globally.

**Comment by sacdallago** [comment]
No need to get upset!
This problems happens quite often, actually! Try the second and third section of the first answer to http://stackoverflow.com/questions/13925916/fatal-error-unable-to-find-local-grunt

**Comment by kajo404** [comment]
Installing grunt locally fixed the problem for me. 
I now get the following result when running `grunt test`

```
>> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
Warning: Task "jshint" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by jcebel** [comment]
Ah yes your right i've forgot... If you've installed everything, you need to install the actually linting-program (for which we are using grunt-contrib-jshint).
With 
npm install grunt-contrib-jshint
it should be running :)
If not maybe you need to install it globally (with the -g option), but this would surprise me.

If it doesn't work, feel free to ask again, I'm not upset that I need to help here. Maybe a little frustrated because I always forget the important half to tell you...

**Comment by kajo404** [comment]
Yeeeeeah it works now. Thank you for your help and patience :smiley:
