### ISSUE TITLE
Asynchronous request calls

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#20]
I have an asynchronous POST request to the database of Project A in [this code](https://github.com/Rostlab/JS16_ProjectD_Group5/blob/databaseA-access/db/db-access.js). 

I can't make the program wait for the answer of the request. It just keeps executing with undefined as value. How do I make this work? I want to get the Date String from the Database and then transform it to the javascript Date format.

**Comment by sacdallago** [comment]
Oh this is one of the most common problems when starting to write code in JS.
transfer all of your logic to the callback function ( https://github.com/Rostlab/JS16_ProjectD_Group5/blob/databaseA-access/db/db-access.js#L24 ).

Btw your code is wrong: airDate is undefined in the scope of 

```
module.exports.getAirDate = function(season, episode){
    airDate(season, episode, makeDateObject);
    console.log(airDate);
}
```

makeDateObject up here is the callback function, that's where you want to put something like:

```
module.exports.getAirDate = function(season, episode){
    airDate(season, episode, function(results){
             console.log(results);
         });
}
```

**Comment by kajo404** [comment]
Thank you for your help. I was able to solve the problem :)
