### ISSUE TITLE
Share schema definition with project A and use same database

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectD_Group5#26]
In an effort to bring together the pieces, we came up with the following requirements:

The schema of what you store about the sentiments of a character needs to be merged with the database of project A.

This can be done in the following fashion:

```
{
  name: "Some character",
  ...,
  D5: {
     // YOUR TWITTER SCHEMA HERE
  },
  D4: {
     // D4's schema
  }
}
```

Where I mean [this](https://github.com/Rostlab/JS16_ProjectD_Group5/blob/develop/db/tweet.js#L5) by your twitter schema.

You will write directly on the database that **A** uses that should be somewhere on mLab. If @kordianbruck is using his own server to store the data, please come up with some idea.. I understand that you are not keen on having an API over mutable data, but until 1 day ago you could get DDosed.. so.. you know :dancer:

@AlexMoroz I assigned the issue to you because **E** should supervise this, but defer commitment to one of your teammates.

**Comment by kajo404** [comment]
Alright I'm on it but what is the reason for using different schemas for
each group? We could effectively double the data by just using one.

**Comment by AlexMoroz** [comment]
@jonny3576 assign it to yourself =)
I don't have access to the repo.

**Comment by sacdallago** [comment]
@kajo404 you and the other D (no pun intended) have two different takes on what to store, why, how to calculate the sentiment score and how to represent it in a visualisation library. If you create one single schema, the question of who's info will be taken will stay anyway. We think that in the end the outcome is gonna be weighted but we'll see how F implements this.

**Comment by kajo404** [comment]
[discussion with project F](https://github.com/Rostlab/JS16_ProjectF/issues/31)
[discussion with group 4](https://github.com/Rostlab/JS16_ProjectD_Group4/issues/21)

for reference

**Comment by kajo404** [comment]
@sacdallago I have one follow up question. Here is what we want to store in A's database for every character:   Date,positiveSent,negativeSent,#posTweets,#negTweets,#nullTweets

We want to store this informartion for every day (well not every day but the days we gather data for :))

How do we realize this with the schema above? For example for Jon Snow we want to store a list like this:

12.11.2015,12,32,5,23,65;
13.11.2015,43,67,23,86,22;
...

This will become quite a list. Is it realistic to store it in a single string that we edit ? Or is there a more intelligent way to do this?

**Comment by sacdallago** [comment]
No, it's not.
If this is the case, use the same database but define a schema that won't overlap with anything already existing (aka: if they have a schema definition "character", you shouldn't call your schema definition "character"). But the API to access the data will be on A's side.. Clear?

**Comment by kajo404** [comment]
Okay thank you I will get in touch with the guys from A about this

**Comment by kajo404** [comment]
Status update: Still waiting on response from A

**Comment by sacdallago** [comment]
I saw a push a couple hours before you wrote this. How is it standing?

**Comment by jcebel** [comment]
we are waiting for the query urls at the moment.

**Comment by kajo404** [comment]
everything working now
