### ISSUE TITLE
Configurable endpoints

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectD_Group5#47]
Hey guys,

please, don't rely on any existing endpoint. Your package needs to be as independent as possible (especially because I'm gonna ask Bruck to tear down the server to see if everything is still working). Specifically I refer to: https://github.com/Rostlab/JS16_ProjectD_Group5/blob/develop/db/dbA.js#L36

You can do something like **C10** did: https://github.com/Rostlab/JS16_ProjectC_Group10/wiki/Init-New-GoT-Map-and-Options

**Comment by kajo404** [comment]
I will add these options to our configuration setup that we are already using for the other database and twitter later today.
