### ISSUE TITLE
Twitter, database, token

### ISSUE THREAD

**Issue by jorjo1** [Rostlab/JS16_ProjectD_Group5#48]
Hello,

I am just trying to set up `gotdailysentiment`. I stumble upon this problem that I need to test it out somehow. Could you please tell me if the database is up and if so, can I get some credentials to test?

Thanks!

**Comment by jcebel** [comment]
As @kajo404 manages the special database He needs to give You Access.. I think we have to work on a smarter solution for project E Jonas :-) no significant changes just an easier way to Access and initalize the package.
@jorjo1: the Team will have a Meeting tomorrow. So maybe You need patience till tomorrow evening, when something will arise, but they work very Hard to supplie You As soon As possible. Stay tuned!

**Comment by sacdallago** [comment]
Hey guys,
since I read that you are meeting: I'm gonna be out for the day. If anything comes up and you need me write here and send the link to the issue on http://dallago.mtalk.net

Peace.

**Comment by jcebel** [comment]
Ah it's quite complicated... At the moment the package is not working, so there is no interest for you for the configuration-file ...
With the next deploy (I hope this will come tomorrow) the oackage should be ready for testing from your side

**Comment by jcebel** [comment]
We are not quite finished figuring out which configuration data will be needed, but I think @kajo404 will give them to you as soon everything is ready to go ;)

**Comment by sacdallago** [comment]
Good. This is why there is some time between feature freeze and deadline! The devil lies in the details :D

**Comment by jcebel** [comment]
Hey @jorjo1
The new package is only and provides you with the dummie functionality. If you want to test it out right now you can just use the content of the [dummieconfig file](https://github.com/Rostlab/JS16_ProjectD_Group5/blob/develop/cfg/configDUMMY.json) and pass it to the init function. 
You will get the real credentials tomorrow I think. Good night and have fun!

**Comment by jcebel** [comment]
Hey sorry i lost it a little Bit in the last days... 
@jorjo1 did You get the config Data? Then feel free to close this issue..

**Comment by kajo404** [comment]
no he didn't how can I send it to you @jorjo1 ?

**Comment by kajo404** [comment]
@jorjo1 Is this still an issue? Tell me how to send you the config file if you need it
