### ISSUE TITLE
config is not defined

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectD_Group5#54]
Please fix

```
/home/yasar/Workspace/web/jsseminar/JS16_ProjectF/node_modules/gotdailysentiment/main.js:7
            fs.writeFileSync(params, JSON.stringify(config, null, 4), function (err) {
                                                    ^
ReferenceError: config is not defined

```

**Comment by jcebel** [comment]
yeah there are more bugs then this one. Testing has just started.. Thanks for sharing :)

**Comment by jcebel** [comment]
There are still some implementation issues.. I'm sorry but we have to wait for @Logarythms till he removed the whole TwitterDB from the code, before the next deployment will be available...
But the reported bug is fixed.

**Comment by kajo404** [comment]
Closing since reported bug is fixed
