### ISSUE TITLE
Bug in init

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectD_Group5#59]
At the [init](https://github.com/Rostlab/JS16_ProjectD_Group5/blob/develop/main.js): the boolean configured needs to be set true at the end of the init-function, because if an error arises inside of the function after the configure value has been set true you have to stop the whole node -instance on which it is running....

**Comment by kajo404** [comment]
https://github.com/Rostlab/JS16_ProjectD_Group5/commit/e63b5e782d21fe175691dd678dca2189b1d9fbf7

is this what you had in mind?

**Comment by jcebel** [comment]
Yes
