### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#6]
EDIT: We will NOT use diskDB anymore. We will use [mlab](https://mlab.com/). Project E has been notified.

We will be using [diskDB](https://www.npmjs.com/package/diskdb) for storing the Information gathered from tweets. It stores the information in a json file on disk. 

The idea is to create a new json file for each api call. The dataset can then be used to create a graph.

Information stored in the database will be:
- Unique Tweet ID
- Character Name (or searchTerm used to query the api)
- Date of the tweet in Javascript Date format
- Sentiment score

**Comment by sacdallago** [comment]
Interesting db choice!

**Comment by kajo404** [comment]
Database is ready to use!
