### ISSUE TITLE
File write problem

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectD_Group5#60]
@yashha suggests the following, so people get no problem if the config.json does not exist at the beginning.
Please implement or at least comment on this proposal if your not gonna implement it

``` javascript
fs.writeFileSync(require('path').resolve(__dirname, 'cfg/config.json'), JSON.stringify(params, null, 4));
statt
fs.writeFileSync('cfg/config.json', JSON.stringify(params, null, 4));

main.js L:7
```

**Comment by kajo404** [comment]
@yashha my current solution is:

```
fs.writeFileSync(require('path').resolve('./cfg/config.json'), JSON.stringify(params, null, 4));
```

I don't know what the purpose if the `__dirname` variable is. Can you explain?

**Comment by yashha** [comment]
https://nodejs.org/api/globals.html#globals_dirname

**Comment by kajo404** [comment]
alright thanks

**Comment by yashha** [comment]
Can you fix it today? important! :)

**Comment by kajo404** [comment]
There is a fix in the current pull request. I don't know if it helps because our database access is still messed up due to missing information from A about token / post requests

**Comment by yashha** [comment]
Thanks :)
