### ISSUE TITLE
Please finish up index.js

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#71]
We need it ready to merge to develop preferably today so we can start testing

**Comment by jcebel** [comment]
@vanp33 I've looked at your test results from Travis...
Maybe one reason that you are not keen to merge at the moment are some communication problems: So please look [here](https://travis-ci.org/Rostlab/JS16_ProjectD_Group5/branches). There are the test results of all branches (navigate to your branch). 
There in the console is some meaningful data printed out about the tests...
Maybe this helps you to find the reason that at the moment there is always an X at your PR.

**Comment by vanp33** [comment]
[here](https://travis-ci.org/Rostlab/JS16_ProjectD_Group5/builds/119241663)  is the errors we got, i think we need to talk to find out why the response is so ridiculous

**Comment by kajo404** [comment]
I deleted the useless console.logs so testing should be clearer now if you pull the changes from develop

**Comment by kajo404** [comment]
Dat got it working, so I'll close this now
