### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectD_Group5#75]
Can I get an example how the config has to be filled in? please :)

```
      "airDateURL": "xxxxx",
      "characterNamesURL": "xxxxx",
      "sentimentSave": "xxxxx",
      "sentimentGetChar": "xxxxx",
      "sentimentGetAll": "xxxxx"
```

**Comment by kajo404** [comment]
The old database is down https://github.com/Rostlab/JS16_ProjectA/issues/125#event-606878720 

I am waiting for the new configuration token. I can email you the config file once it is updated. What is your email adress?

**Comment by kajo404** [comment]
It is ready now, just waiting on information on how to send it to you

**Comment by kajo404** [comment]
sent
