### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#76]
Hey @sacdallago I need your help :)
1. What should I if errors occur during saving to the database. Is it okay to just console.log the error and keep on truckin?
2. If an error occurs during a get request to the database (like connection time out) is it okay to return an empty json and just console.log the error message?
3. Can I get the new token for the database?

**Comment by sacdallago** [comment]
1. It depends on what kind of error. Some errors need to break the app, that's just how it is. But the one that you seem to be reporting, doesn't seem to be such error **EDIT**: thus, yes: console.**error** (not log) and keep on going
2. Are you directly manipulating responses? Aka: can you `send()` responses? Either way there is an appropriate [Error code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) for everything. Your situation suggest 503 to me.
3. Send me an email please

**Comment by kajo404** [comment]
1. Will do
2. Not directly manipulating but we get the error codes from the database, do we just pass them to the callback function? And if so, where do we deal with the errors?
3. Sent (to the email adress you listed on github)

**Comment by sacdallago** [comment]
Answer to 2. : Callbacks usually accept two arguments, first one the result and second the error:
Successful calls end in:

``` javascript
callback(result);
```

the ones that delegate and error:

``` javascript
callback(undefined, error);
```

You **can** also `throw` an error to be caught by who implements the API. It's a design choice. I'd stick to the callback way of handling such errors.

**Comment by kajo404** [comment]
That would mean we need to change documentation and this will also affect Project F. Is this okay after feature freeze?

**Comment by sacdallago** [comment]
If it's unavoidable

**Comment by jcebel** [comment]
wouldn't be an unbelievable complicated change. We already discussed the errors with F just how to determine if an error occurs is slightly different. 
To pass a second parameter to the function is in JS not that complicated as it is in other languages.
