### ISSUE TITLE
Use our awesome logo in the documentation

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#81]

**Comment by kajo404** [comment]
:heart:

**Comment by sacdallago** [comment]
:D It's awesome but for all the ads I've seen so far on got it seems to me a bit too red/bloody?
Actually. IF you make it an evil face? :D :D :D

**Comment by kajo404** [comment]
added to very bottom of priority list. It's so low Flo Rida getting jealous
