### ISSUE TITLE
Suspicious requests

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectD_Group5#82]
Hey guys. Looking at the server logs (of the api) I see a bunch of:

``` bash
[Wed Mar 30 2016 00:01:50] [LOG]   [Worker 4] Request incoming: /sentiment/find
[Wed Mar 30 2016 00:01:50] [LOG]   [Worker 4] 401 - no token sent
```

Between 21:47 and 1:50. I don't know if this was you, the other twitter group, or someone else. I just wanted to report, in case you were having some issues or spontaneous exceptions in your code, this might be the reason!

**Comment by sacdallago** [comment]
I'm still getting a lot of these right now:

``` bash
[Wed Mar 30 2016 10:25:37] [LOG]   [Worker 7] Request incoming: /sentiment/find
[Wed Mar 30 2016 10:25:37] [LOG]   [Worker 7] 401 - no token sent
```

If you are working on this, please let me now ASAP so we can pinpoint the problem

**Comment by kajo404** [comment]
Not us

**Comment by sacdallago** [comment]
Thx

**Comment by kajo404** [comment]
Could be us :D

**Comment by jcebel** [comment]
Could be me... I'm testing locally the appplication at the moment

**Comment by jcebel** [comment]
But I'm using a token... That's odd.

**Comment by jcebel** [comment]
But since when do I need the Token for find?

**Comment by sacdallago** [comment]
:D Let's do it like this. Send a request and tell me the exact time, I'll check the logs

**Comment by jcebel** [comment]
Ok I start the request now
It'S 10:41 am

**Comment by sacdallago** [comment]
If the request is not a GET, you need a token

**Comment by sacdallago** [comment]
``` bash
[Wed Mar 30 2016 10:40:14] [LOG]   [Worker 1] Request incoming: /sentiment/find?token=got-very-secure-token-no-one-will-ever-actually-guess
[Wed Mar 30 2016 10:40:14] [LOG]   [Worker 1] 401 - wrong token sent
[Wed Mar 30 2016 10:40:16] [LOG]   [Worker 3] Request incoming: /sentiment/find?token=got-very-secure-token-no-one-will-ever-actually-guess
[Wed Mar 30 2016 10:40:16] [LOG]   [Worker 3] 401 - wrong token sent
[Wed Mar 30 2016 10:40:16] [LOG]   [Worker 8] Request incoming: /sentiment/find?token=got-very-secure-token-no-one-will-ever-actually-guess
[Wed Mar 30 2016 10:40:16] [LOG]   [Worker 8] 401 - wrong token sent
[Wed Mar 30 2016 10:40:16] [LOG]   [Worker 4] Request incoming: /sentiment/find?token=got-very-secure-token-no-one-will-ever-actually-guess
[Wed Mar 30 2016 10:40:16] [LOG]   [Worker 4] 401 - wrong token sent
[Wed Mar 30 2016 10:40:18] [LOG]   [Worker 5] Request incoming: /sentiment/byTimeRange?beginDate=startdate&endDate=enddate
[Wed Mar 30 2016 10:40:20] [LOG]   [Worker 2] Request incoming: /sentiment/byTimeRange?beginDate=startdate&endDate=enddate
[Wed Mar 30 2016 10:40:22] [LOG]   [Worker 6] Request incoming: /sentiment/byTimeRange?beginDate=startdate&endDate=enddate
[Wed Mar 30 2016 10:40:24] [LOG]   [Worker 7] Request incoming: /sentiment/byTimeRange?beginDate=startdate&endDate=enddate
```

**Comment by jcebel** [comment]
If it stopped now It should be us

**Comment by sacdallago** [comment]
also.. `startdate` and `enddate` are not really meaningful? :D I don't know if this is actually matched by anything in the db, but it looks extremely suspicious to me

**Comment by sacdallago** [comment]
To sort this problem out, the best thing you can do is to run the API locally. Setup takes about 15 minutes and I can send you the config via email. Let me now

**Comment by jcebel** [comment]
Ok we're working on it.. Problem of copy and paste and some other stuff

**Comment by jcebel** [comment]
maybe it would be helpful if we run it locally.. Could you send me the token @sacdallago

**Comment by sacdallago** [comment]
@jonny3576 you mean the config? Can you send me an email? :laughing: 
If you don't know:
1. Clone [A](git@github.com:Rostlab/JS16_ProjectA.git)
2. npm install
3. Copy the config I'm gonna send you per email to the 'cfg' folder
4. Start the app via `node app`

that's all you need to do.

**Comment by jcebel** [comment]
Yes I will do :)
And this suspicious requests will come some time now until this bug is fixed in the testing. Please be patient.

**Comment by sacdallago** [comment]
Of course :dancer: 
I'm just happy these things pop up :) This is why it's important to always run everything locally :P

**Comment by jcebel** [comment]
@sacdallago I don't have to do all steps from Project A in the Documentation since it isn't running on their server anymore or do I?
What I mean is do I have to set the database.port to the value you send me or to the value which is in the documentation?

**Comment by sacdallago** [comment]
You can set the port to whatever you want, it's gonna run locally.. Instead of the server address alone you'll then need to put the port like `localhost:8080` or whatever.
U don't need to run the fillers nor anything else. You can just Clone, put the DB config i sent u, put the Twitter keys and `node app` the log will then tell u where the API is listening and what token u need

**Comment by jcebel** [comment]
ok yes.. In the seconde you answered it was fixed :D Thanks!

**Comment by jcebel** [comment]
@kajo404 @Logarythms @vanp33: When I'm running the test branch locally with the local database I don't get the errors anymore so this is fixed (locally). The tests are still failing with the same errormessage as it is [here](https://travis-ci.org/Rostlab/JS16_ProjectD_Group5/builds/119484504). 
Please have a look at your code:
@sacdallago I would close this issue as soon as I'm merging the test branch to develop (should be happening in three hours). Hope the suspicious requests get less and less over the day. When I close it it means, that I think it should be resolve. If you could check the locks then.

**Comment by sacdallago** [comment]
Make sure it works from your side. The dev in project F might not have the latest npm updated version of your package so I'll get sporadic messages. But if you are sure you fixed this issue, no need to bother, close here and I'll come back should anything alerting happen!
