### ISSUE TITLE
Feature freeze and testing 

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectD_Group5#91]
@sacdallago @yashha (please add the other tutors. Can't remember the names and with my mobile I don't get the suggestions)
We have discovered a Major Design error as we started the testing in Index.js (this is the Ui).
All functions get a json in which the User specifies the search query(e.g. Name of character, date etc.)
The Problem is that the propertyname where the charactername gets stored is unconsistent (it's  sometimes Name, charactername or just character).
Also the response json contains a property where the character Name gets stored. There also unconsistency over the whole application.
We want to change all property-names to "character" if it is ok to Do such a Major change After Feature freeze.
We would Do that in heavy cooperation with F as they are the Main USER of the App at the moment.
Please respond with any thoughts questiona etc.

**Comment by sacdallago** [comment]
This needs to be done. It's unthinkable to have inconsistent data at the first release :D

**Comment by sacdallago** [comment]
P.S.: in FF you stop implementing features and try to avoid changing the functionality, but if stuff like this comes up, you un-try to avoid it :laughing: Also, I don't think it's such a major change for the end user, it's actually a simplification.

End of the story: just do it and let **F** know when it's done, possibly sooner than later

**Comment by kajo404** [comment]
On it

**Comment by jcebel** [comment]
@yashha I just saw that I did not write it in the notification, but this has also been change with the deployment yesterday. Please consult the readme or me if you're having questions :)
