### ISSUE TITLE
Stored Data Fail

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectD_Group5#94]
Hey @sacdallago and @togiberlin,
Project D 5 stored some data as a negativ value though it should be stored positive.
Now we wrote the following script to resolve that problem using the edit-url of the database.

``` javascript
var request = require('request');

var allURL = "https://api.got.show/api/sentiment";
var changeURL ="https://api.got.show/api/sentiment/edit/:id?token=xxx";

request.get(allURL, function(err, resp, body){
   var json = JSON.parse(body);
   json.forEach(function(currentValue, index, array){
       if(currentValue.negSum < 0){
           currentValue.negSum = currentValue.negSum * (-1);
       }
       if(currentValue.negCount < 0){
           currentValue.negCount = currentValue.negCount * (-1);
       }
       changeURL = changeURL.replace('id',currentValue._id);
       request({
           method: "PUT",
           uri: changeURL,
           form: {
               'negSum' : currentValue.negSum,
               'negCount' : currentValue.negCount
           }
       }, function(err, resp, body){
           console.error(err);
           console.log(body);
       });
   });
});
```

Nothing happens and works. Is it possible that there is an intern error in the code of Project A. What does the log say @sacdallago. When I run it locally it says the following:

```
[Fri Apr 01 2016 12:57:48]C:\Users\jonas\Documents\GitHub\JS16_ProjectA\app\stores\charactersSentiment.js:127
                callback(2, id);
                ^

TypeError: callback is not a function
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\app\stores\charactersSentiment.js:127:17
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\app\stores\charactersSentiment.js:94:17
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\app\stores\charactersSentiment.js:41:17
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\node_modules\mongoose\node_modules\kareem\index.js:160:11
    at Query._find (C:\Users\jonas\Documents\GitHub\JS16_ProjectA\node_modules\mongoose\lib\query.js:1018:5)
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\node_modules\mongoose\node_modules\kareem\index.js:156:8
    at C:\Users\jonas\Documents\GitHub\JS16_ProjectA\node_modules\mongoose\node_modules\kareem\index.js:18:7
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by sacdallago** [comment]
My log will most likely say the exact same thing, as the code-base is the same.
The file is not interpreting callback as a function. This can depend either on A or you, @boriside @kordianbruck @togiberlin please have a look at the three lines in the stack and report back ASAP. (thx)

**Comment by sacdallago** [comment]
Yes. The code breaks also on my machine.

``` bash
[Fri Apr 01 2016 12:55:33] [LOG]   [Worker 575] Request incoming: /sentiment/edit/:yyy?token=xxx
/home/cdallago/api/app/stores/charactersSentiment.js:127
                callback(2, id);
                ^

TypeError: callback is not a function
    at /home/cdallago/api/app/stores/charactersSentiment.js:127:17
    at /home/cdallago/api/app/stores/charactersSentiment.js:94:17
    at /home/cdallago/api/app/stores/charactersSentiment.js:41:17
    at /home/cdallago/api/node_modules/kareem/index.js:160:11
    at Query._find (/home/cdallago/api/node_modules/mongoose/lib/query.js:1018:5)
    at /home/cdallago/api/node_modules/kareem/index.js:156:8
    at /home/cdallago/api/node_modules/kareem/index.js:18:7
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
[Fri Apr 01 2016 12:55:33] [LOG]   [MASTER] worker 3844 died
```

**Comment by jcebel** [comment]
Okay the tests are passing now, but now we can't use the stored data. 
As workaround we can delete the wrong data. But it would be a shame to do that, because Project F won't be able to play around with the application.

**Comment by sacdallago** [comment]
I don't quite get what you are saying?

**Comment by kajo404** [comment]
The wrong data fucks up our tests. To publish the package we need to pass all the tests. We either delete the wrong data(which is most of the valuable data => not 0) or we alter the tests which kind of defies the purpose of testing?

**Comment by sacdallago** [comment]
Can't you normalize the data? Where does the error get generated?

**Comment by jcebel** [comment]
The problem is that the data should be a positive number, but it isn't. That was a mistake but now it won't happen again. There is still the old data, which we are using for testing but we are expecting it in the  tests to be positive, so either I will skip this specific tests or i make them less expressive. Both would be not my favorite way to go. Especially because we had to delete the wrong data from the database after publishing. 
In theory it wouldn't be hard I think to write a script to override the wrong data. (Just ´x*(-1)´ ).
BUT the edit function seems to fail inside of Project A. 
So we wait at the moment.

**Comment by sacdallago** [comment]
Yes. That doesn't look like a wayyyyy to difficult thing to do to me if the value is actually stored as a number (not string). And I'm talking plain mongo here, forget the whole js story for a moment.
1. https://docs.mongodb.org/manual/reference/method/db.collection.update/
2. https://docs.mongodb.org/manual/reference/operator/update/mul/#up._S_mul

**Comment by jcebel** [comment]
But.... But... This is a js-seminar :sob:

**Comment by jcebel** [comment]
we will look into it.

**Comment by Logarythms** [comment]
Do we have direct access to Project A's mongoDB?

**Comment by jcebel** [comment]
@sacdallago ?

**Comment by kordianbruck** [comment]
If there is an issue with the API, please open a Issue in A's bug tracker. 

@Logarythms You can ask @sacdallago for DB access, he will gladly provide it :tada: :dancer:

**Comment by sacdallago** [comment]
I need an email guys.. And I'm gonna be away for 2h in 10 mins :D

**Comment by Logarythms** [comment]
@sacdallago camille.mainz@gmail.com

**Comment by kajo404** [comment]
prepare for your database to ripped to pieces when you return

**Comment by sacdallago** [comment]
Done
