### ISSUE TITLE
Unknown Country Codes

### ISSUE THREAD

**Issue by togiberlin** [Rostlab/JS16_ProjectD_Group5#97]
Hello,

I'm currently looking through your [Twitter language data](https://docs.google.com/spreadsheets/d/1Z4V3Sj3KQu_YgEac2NqqLKoReWrHafucbHCGDfmw3As/edit?usp=sharing) and there are 3 country codes, which I don't get.
What does `IN`, `und` and `cy` mean? Indonesian? Undefined? Welsh?

**Comment by sacdallago** [comment]
AHAHAH

**Comment by kajo404** [comment]
never seen this file before, maybe its from D4 ?

**Comment by gyachdav** [comment]
yup my bad i sent @togiberlin here. should've been posted on D5 issues
